Установим 

In [1]:
# pip install numpy

Импортируем модуль Numpy

In [2]:
import numpy as np

NumPy реализует массивы (ndarray), которые похожи на списки (list) в python, однако операции с ними происходят гораздо быстрее

In [3]:
a=[1,2,3]
print("a: ",type(a))

b=np.array([4,5,6])
print("b: ",type(b))

a:  <class 'list'>
b:  <class 'numpy.ndarray'>


Создадим два списка list1 и list2 с помощью команды range(), также создадим два массива с помощью np.arange()

In [4]:
N = 1000000
  
list1 = range(N)
list2 = range(N)
  
array1 = np.arange(N)
array2 = np.arange(N)


Создадим список list3, i-ый элемент которого будет равен произведению i-ых элементов списков list1 и list2. Посмотрим время выполнения этой операции

In [5]:

%time list3 = [(a * b) for a, b in zip(list1, list2)]


CPU times: total: 109 ms
Wall time: 120 ms


То же самое проделаем для массивов array1 и array2

In [6]:
%time array3 = array1 * array2

CPU times: total: 15.6 ms
Wall time: 5.98 ms


Зададим два массива и выведем их значения

In [7]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print('a: ',a)
print('b: ',b)

a:  [1 2 3]
b:  [4 5 6]


Заметим, что основные операции выполняются поэлементно

In [8]:
print('a+b: ',a+b)
print('a-b: ',a-b)
print('a*b: ',a*b)
print('a/b: ',a/b)
print('a^b: ',a**b)

a+b:  [5 7 9]
a-b:  [-3 -3 -3]
a*b:  [ 4 10 18]
a/b:  [0.25 0.4  0.5 ]
a^b:  [  1  32 729]


Массивы могут быть многомерными, в таком случае их можно рассматривать как "массив массивов"

In [9]:
a=np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


Узнать размерность массива можно с помощью команды np.shape() или атрибута .shape

In [10]:
print(np.shape(a))
print(a.shape)

(3, 2)
(3, 2)


В некоторых задачах требуется изменить размерность массива, в таком случае используется команда np.reshape()

In [11]:
print(a)
print(np.reshape(a,[2,3]))

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


Некоторые функции можно определять для различных осей массива (axis), посмотрим это на примере функции np.max()

In [12]:
print(np.max(a))
print(np.max(a,axis=0))
print(np.max(a,axis=1))

6
[5 6]
[2 4 6]


In [13]:
print(np.sum(a))
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

21
[ 9 12]
[ 3  7 11]
